- name: Check if installation directory exists
  ansible.builtin.stat:
    path: "{{ install_dir }}"
  register: idr

- name: Generate SSH key 
  openssh_keypair:
    path: "{{ install_dir }}/ssh/ocplab_rsa"
  when: idr.stat.isdir is defined and idr.stat.isdir 

- name: Check if ssh key is generated as "{{ install_dir }}/ssh/ocplab_rsa.pub"
  ansible.builtin.stat:
    path: "{{ install_dir }}/ssh/ocplab_rsa.pub"
  register: sshpub

- name: Read the SSH public key file
  ansible.builtin.slurp:
    src: "{{ install_dir }}/ssh/ocplab_rsa.pub"
  when: sshpub.stat.exists
  register: sshkey_content

- name: Store the SSH key content in a variable for later use
  set_fact:
    ssh_public_key: "{{ sshkey_content.content | b64decode | trim }}"
  when: sshpub.stat.exists

- name: Output SSH public key for debugging
  ansible.builtin.debug:
    msg: "{{ ssh_public_key }}"
  when: sshpub.stat.exists