apiVersion: v1
baseDomain: lab 
compute: 
- name: worker
  replicas: 0 
controlPlane: 
  name: master
  replicas: 3
metadata:
  name: rhlab 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23
  machineNetwork:
    - cidr: 192.168.0.0/16
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs:
    - 192.168.0.2
    ingressVIPs:
    - 192.168.0.3
fips: false 
pullSecret: '{"auths": ...}' 
sshKey: 'ssh-ed25519 AAAA...' 